"""
Const data base
"""

#GUI Parameters
GUI_TITLE = "TikTacToe Game"

X_SCREEN = 65
Y_SCREEN = 360
GUI_WIDTH = 1200
GUI_HEIGHT = 800

#PLAY_BUTTONS
PLAY_BUTTONS = ["", "", "", "", "", "", "", "", ""]
PLAY_BUTTONS_SPACE = ""
PLAY_BUTTON_NAME = ["A1", "A2", "A3", "B1", "B2", "B3", "C1", "C2", "C3"]

X_ONE_VALUE = 50
Y_ONE_VALUE = 50

PLAY_BUTTON_WIDTH = 200
PLAY_BUTTON_HEIGHT = 200

X_MARGIN = PLAY_BUTTON_WIDTH + 50
Y_MARGIN = PLAY_BUTTON_HEIGHT + 50

X_TWO_VALUE = X_ONE_VALUE + X_MARGIN
X_THR_VALUE = X_TWO_VALUE + X_MARGIN

Y_TWO_VALUE = Y_ONE_VALUE + Y_MARGIN
Y_THR_VALUE = Y_TWO_VALUE + Y_MARGIN

#Style Paramters
BUTTON_BACKGROUND_COLOR = "#323B3E"
WINDOW_BACKGROUND_COLOR = "#FF9900"